const $ = s => document.querySelector(s);
const loginView = $('#loginView'), dashboard = $('#dashboard'), loginForm = $('#loginForm'), loginError = $('#loginError');
let messages = [], filter = 'all';
function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatDate(value){const d=new Date(value);return isNaN(d)?'Unknown date':d.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}
async function api(url, options={}){const r=await fetch(url,options);let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function checkAuth(){try{await api('/api/admin/me');showDashboard();loadMessages()}catch{loginView.classList.remove('hidden');dashboard.classList.add('hidden')}}
function showDashboard(){loginView.classList.add('hidden');dashboard.classList.remove('hidden')}
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginError.textContent='Signing in…';try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#username').value,password:$('#password').value})});loginError.textContent='';showDashboard();loadMessages()}catch(err){loginError.textContent=err.message}});
async function loadMessages(){const list=$('#messageList');list.innerHTML='<div class="loading">Loading messages…</div>';try{messages=(await api('/api/admin/messages')).messages;render()}catch(err){if(err.message==='Unauthorized'){loginView.classList.remove('hidden');dashboard.classList.add('hidden')}else list.innerHTML=`<div class="empty"><h2>Could not load messages</h2><p>${esc(err.message)}</p></div>`}}
function render(){const visible=messages.filter(m=>filter==='all'||(filter==='unread'&&!m.read)||(filter==='read'&&m.read));$('#total').textContent=messages.length;$('#unread').textContent=messages.filter(m=>!m.read).length;$('#latest').textContent=messages[0]?new Date(messages[0].createdAt).toLocaleDateString(): '—';const list=$('#messageList');$('#empty').classList.toggle('hidden',visible.length!==0);list.innerHTML=visible.map(m=>`<article class="message ${m.read?'':'unread'}"><div><div class="message-head"><span class="name">${esc(m.name)}</span>${m.read?'':'<span class="badge">New</span>'}</div><div class="meta"><a href="mailto:${esc(m.email)}" style="color:inherit">${esc(m.email)}</a> · ${formatDate(m.createdAt)}</div><span class="project">${esc(m.project||'General enquiry')}</span><div class="message-text">${esc(m.message)}</div></div><div class="message-actions">${m.read?'':'<button onclick="markRead(\''+m.id+'\')">Mark read</button>'}<button class="delete" onclick="deleteMessage(\''+m.id+'\')">Delete</button></div></article>`).join('')}
window.markRead=async id=>{try{await api('/api/admin/messages/read',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});await loadMessages()}catch(e){alert(e.message)}};
window.deleteMessage=async id=>{if(!confirm('Delete this message permanently?'))return;try{await api('/api/admin/messages',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});await loadMessages()}catch(e){alert(e.message)}};
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()}));
$('#refresh').addEventListener('click',loadMessages);
$('#logout').addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()});
checkAuth();
